---
- name: Install Vector
  hosts: vector
  gather_facts: false
  tasks:
    - name: Debug
      debug:
        msg: "echo 123"
- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: false
  tasks:
    - name: Debug
      debug:
        msg: "echo 234"
- name: Install Lighthouse
  hosts: lighthouse
  tasks:
    - name: Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Install EPEL repo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Clean directory
      become: true
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent
      changed_when: false
    - name: Start nginx service
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: started
        daemon_reload: true
    - name: Clone lighthouse
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        version: master
        dest: /usr/share/nginx/html/
      changed_when: false
    - name: Reload nginx service
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      changed_when: false