version: '3.1'

services:
  db:
    image: postgres:12.11
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dump:/dump

  test_db:
    image: postgres:12.11
    restart: always
    container_name: test_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
      - ./dump:/dump
volumes:
  db-data:
  test-db-data: