---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: "{{ vector_dir }}"
        state: directory
        mode: '0755'
      check_mode: false
      tags:
        - vector
    - name: Download
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.27.0/vector-0.27.0-1.{{ vector_arch }}.rpm"
        dest: "{{ vector_dir }}/vector-0.27.0-1.{{ vector_arch }}.rpm"
      check_mode: false
      tags:
        - vector
    - name: Install package
      become: true
      ansible.builtin.yum:
        name:
          - "{{ vector_dir }}/vector-0.27.0-1.{{ vector_arch }}.rpm"
      tags:
        - vector
    - name: Start vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: started
        daemon_reload: true
      check_mode: false
      ignore_errors: "{{ ansible_check_mode }}"
      tags:
        - vector
- name: Install Lighthouse
  hosts: lighthouse
  tasks:
    - name: Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
      tags:
        - lighthouse
    - name: Install EPEL repo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags:
        - lighthouse
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      tags:
        - lighthouse
    - name: Clean directory
      become: true
      ansible.builtin.file:
        path: "{{ lighthouse_default_dir }}"
        state: absent
      changed_when: false
      tags:
        - lighthouse
    - name: Start nginx service
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: started
        daemon_reload: true
      check_mode: false
      ignore_errors: "{{ ansible_check_mode }}"
      tags:
        - lighthouse
    - name: Clone lighthouse
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        version: master
        dest: "{{ lighthouse_default_dir }}"
      changed_when: false
      tags:
        - lighthouse
    - name: Reload nginx service
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      changed_when: false
      check_mode: false
      tags:
        - lighthouse