---
#- name: Install Vector
#  hosts: vector
#  vars:
#    - vector_dir: "./vector_directory"
#  roles:
#    - vector-role
#- name: Install Clickhouse
#  hosts: clickhouse
#  roles:
#    - clickhouse
- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
      tags:
        - lighthouse
    - name: Install EPEL repo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags:
        - lighthouse
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      tags:
        - lighthouse
  roles:
    - lighthouse-role