kubectl-apply-pod:
	kubectl apply -f ./src/pod.yml

kubectl-apply-service:
	kubectl apply -f ./src/service.yml

kubectl-get-all-pods:
	kubectl get pods -A

kubectl-get-pod:
	kubectl get pod netology-web

kubectl-describe-pod:
	kubectl describe pod netology-web

kubectl-port-forward-pod:
	kubectl port-forward netology-web :80

kubectl-get-service:
	kubectl get service

kubectl-describe-service:
	kubectl describe service netology-svc

kubectl-port-forward-service:
	kubectl port-forward svc/netology-svc 8080:80