version: '3.1'

services:
  clickhouse-01:
    image: pycontribs/centos:7
    container_name: clickhouse-01
    command: sleep 600000000

  vector-01:
    image: pycontribs/centos:7
    container_name: vector-01
    command: sleep 600000000