version: '3.1'

services:
  clickhouse-01:
    image: pycontribs/centos:7
    container_name: clickhouse-01
    privileged: true
    command: "sleep 99999999"
  vector-01:
    image: pycontribs/centos:7
    container_name: vector-01
    privileged: true
    entrypoint: [ "/usr/sbin/init" ]
  lighthouse-01:
    image: pycontribs/centos:7
    container_name: lighthouse-01
    privileged: true
    entrypoint: [ "/usr/sbin/init" ]