version: '3.1'

services:
  elasticsearch:
    image: hitenok/elasticsearch_netology:0.0.2
    build:
      context: docker/elasticsearch
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data

volumes:
  elasticsearch-data: