up:
	docker-compose up -d

down:
	docker-compose down

build:
	docker-compose build

push:
	docker-compose push

pull:
	docker-compose pull

down-clear:
	docker-compose down --volume

elasticsearch-bash:
	docker exec -it elasticsearch bash