version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./test_data:/dump

volumes:
  db-data: