filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["es-hot:9200"]
#  hosts: [ "http://localhost:9200" ]
  index: "logstash-%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
#  hosts: ["logstash:5046"]

logging.json: true
logging.metrics.enabled: false