---
all:
  hosts:
    sonar-01:
#      ansible_host: <somehost2>
      ansible_connection: docker
    nexus-01:
#      ansible_host: <somehost>
      ansible_connection: docker
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ansible